before_install:
    - git clone https://github.com/sstephenson/bats.git
    - cd bats
    - sudo ./install.sh /usr/local
    - cd ..
    - go get github.com/mattn/gom
script:
    - $HOME/gopath/bin/gom install -x
    - $HOME/gopath/bin/gom test -x
install: make all
language: go
go:
- 1.4
- 1.3
